---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1 hello

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

##step 12.3

- Wyatt's note: This was very straight forward as I have used git multiple times. 

- Jensen: This is my first time using git so I am pretty confused.

-Bhavika: This is new for me as well.

- Yash: I have used Git before, but I have to get used to the interface again as I haven't used it in a while.

##step 12.4

- Wyatt's note: This part is the same logic as using a git terminal. 
I just dont have to type the commands, just have to get used to pushing the buttons.

- Jensen: This is a line from RStudio. This was very educational on how to use git.

-Bhavika: This is a line from RStudio

- Yash: This is a line from RStudio.


